name: Build and Deploy

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'
      
      - name: Get dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Upload build
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ng_deploy
          path: dist
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Download build
        uses: actions/download-artifact@v2.0.9
        with:
          name: ng_deploy
          
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: twitch-drop-campaigns-ui
          
